import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Main from "@/app/pages/main/page";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Main />
        {children}
      </body>
    </html>
  );
}
